import Database from "better-sqlite3";
import path from "path";
import fs from "fs";

const DB_DIR = path.join(process.cwd(), "data");
const DB_PATH = path.join(DB_DIR, "ikkfms.db");

if (!fs.existsSync(DB_DIR)) {
  fs.mkdirSync(DB_DIR, { recursive: true });
}

const db = new Database(DB_PATH);
db.pragma("journal_mode = WAL");
db.pragma("foreign_keys = ON");

// Create tables
db.exec(`
  CREATE TABLE IF NOT EXISTS families (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_name TEXT NOT NULL,
    head_nik TEXT NOT NULL UNIQUE,
    head_name TEXT NOT NULL,
    head_birth_place TEXT,
    head_birth_date TEXT,
    head_gender TEXT DEFAULT 'Laki-laki',
    head_job TEXT,
    head_education TEXT,
    head_phone TEXT,
    home_address TEXT,
    wife_name TEXT,
    created_at TEXT DEFAULT (datetime('now', 'localtime')),
    updated_at TEXT DEFAULT (datetime('now', 'localtime'))
  );

  CREATE TABLE IF NOT EXISTS members (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    family_id INTEGER NOT NULL,
    nik TEXT NOT NULL,
    name TEXT NOT NULL,
    birth_place TEXT,
    birth_date TEXT,
    gender TEXT,
    family_status TEXT NOT NULL DEFAULT 'Anak',
    job TEXT,
    education TEXT,
    phone TEXT,
    child_order INTEGER,
    created_at TEXT DEFAULT (datetime('now', 'localtime')),
    updated_at TEXT DEFAULT (datetime('now', 'localtime')),
    FOREIGN KEY (family_id) REFERENCES families(id) ON DELETE CASCADE
  );
`);

// Clear existing data
db.exec("DELETE FROM members");
db.exec("DELETE FROM families");
db.exec("DELETE FROM sqlite_sequence WHERE name='families' OR name='members'");

const insertFamily = db.prepare(`
  INSERT INTO families (family_name, head_nik, head_name, head_birth_place, head_birth_date,
    head_gender, head_job, head_education, head_phone, home_address, wife_name)
  VALUES (@family_name, @head_nik, @head_name, @head_birth_place, @head_birth_date,
    @head_gender, @head_job, @head_education, @head_phone, @home_address, @wife_name)
`);

const insertMember = db.prepare(`
  INSERT INTO members (family_id, nik, name, birth_place, birth_date,
    gender, family_status, job, education, phone, child_order)
  VALUES (@family_id, @nik, @name, @birth_place, @birth_date,
    @gender, @family_status, @job, @education, @phone, @child_order)
`);

const families = [
  {
    family_name: "Keluarga Mone",
    head_nik: "9201140101750001",
    head_name: "Yohanes Mone",
    head_birth_place: "Sorong",
    head_birth_date: "1975-01-01",
    head_gender: "Laki-laki",
    head_job: "PNS",
    head_education: "S1",
    head_phone: "081234567890",
    home_address: "Jl. Basuki Rahmat No. 12, Sorong",
    wife_name: "Maria Feto",
    members: [
      {
        nik: "9201140201780002",
        name: "Maria Feto",
        birth_place: "Sorong",
        birth_date: "1978-02-14",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Ibu Rumah Tangga",
        education: "SMA/SMK",
        phone: "081234567891",
        child_order: null,
      },
      {
        nik: "9201140301000003",
        name: "Andreas Mone",
        birth_place: "Sorong",
        birth_date: "2000-03-15",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Mahasiswa",
        education: "SMA/SMK",
        phone: "081234567892",
        child_order: 1,
      },
      {
        nik: "9201140401030004",
        name: "Theresia Mone",
        birth_place: "Sorong",
        birth_date: "2003-04-22",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMA/SMK",
        phone: null,
        child_order: 2,
      },
      {
        nik: "9201140501080005",
        name: "Petrus Mone",
        birth_place: "Sorong",
        birth_date: "2008-05-10",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMP",
        phone: null,
        child_order: 3,
      },
    ],
  },
  {
    family_name: "Keluarga Feto",
    head_nik: "9201140601700006",
    head_name: "Dominggus Feto",
    head_birth_place: "Sorong",
    head_birth_date: "1970-06-08",
    head_gender: "Laki-laki",
    head_job: "Wiraswasta",
    head_education: "SMA/SMK",
    head_phone: "082345678901",
    home_address: "Jl. Ahmad Yani No. 45, Sorong",
    wife_name: "Agustina Bano",
    members: [
      {
        nik: "9201140701730007",
        name: "Agustina Bano",
        birth_place: "Sorong",
        birth_date: "1973-07-20",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Pedagang",
        education: "SMP",
        phone: "082345678902",
        child_order: null,
      },
      {
        nik: "9201140801950008",
        name: "Markus Feto",
        birth_place: "Sorong",
        birth_date: "1995-08-12",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Karyawan Swasta",
        education: "S1",
        phone: "082345678903",
        child_order: 1,
      },
      {
        nik: "9201140901970009",
        name: "Yuliana Feto",
        birth_place: "Sorong",
        birth_date: "1997-09-05",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Guru",
        education: "S1",
        phone: "082345678904",
        child_order: 2,
      },
    ],
  },
  {
    family_name: "Keluarga Sorong",
    head_nik: "9201141001680010",
    head_name: "Paulus Sorong",
    head_birth_place: "Manokwari",
    head_birth_date: "1968-10-25",
    head_gender: "Laki-laki",
    head_job: "Nelayan",
    head_education: "SD",
    head_phone: "083456789012",
    home_address: "Jl. Pantai Indah No. 7, Sorong",
    wife_name: "Naomi Mone",
    members: [
      {
        nik: "9201141101720011",
        name: "Naomi Mone",
        birth_place: "Sorong",
        birth_date: "1972-11-03",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Ibu Rumah Tangga",
        education: "SD",
        phone: "083456789013",
        child_order: null,
      },
      {
        nik: "9201141201930012",
        name: "Samuel Sorong",
        birth_place: "Sorong",
        birth_date: "1993-12-18",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Nelayan",
        education: "SMP",
        phone: "083456789014",
        child_order: 1,
      },
      {
        nik: "9201140102960013",
        name: "Ruth Sorong",
        birth_place: "Sorong",
        birth_date: "1996-01-07",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Pedagang",
        education: "SMA/SMK",
        phone: "083456789015",
        child_order: 2,
      },
      {
        nik: "9201140202990014",
        name: "Daniel Sorong",
        birth_place: "Sorong",
        birth_date: "1999-02-28",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Mahasiswa",
        education: "SMA/SMK",
        phone: null,
        child_order: 3,
      },
      {
        nik: "9201140302040015",
        name: "Esther Sorong",
        birth_place: "Sorong",
        birth_date: "2004-03-14",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMP",
        phone: null,
        child_order: 4,
      },
    ],
  },
  {
    family_name: "Keluarga Bano",
    head_nik: "9201140402720016",
    head_name: "Stefanus Bano",
    head_birth_place: "Sorong",
    head_birth_date: "1972-04-19",
    head_gender: "Laki-laki",
    head_job: "Petani",
    head_education: "SMP",
    head_phone: "084567890123",
    home_address: "Jl. Cendrawasih No. 23, Aimas, Sorong",
    wife_name: "Magdalena Krey",
    members: [
      {
        nik: "9201140502750017",
        name: "Magdalena Krey",
        birth_place: "Sorong",
        birth_date: "1975-05-11",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Petani",
        education: "SD",
        phone: "084567890124",
        child_order: null,
      },
      {
        nik: "9201140602980018",
        name: "Viktor Bano",
        birth_place: "Sorong",
        birth_date: "1998-06-30",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Karyawan Swasta",
        education: "SMA/SMK",
        phone: "084567890125",
        child_order: 1,
      },
      {
        nik: "9201140702010019",
        name: "Siska Bano",
        birth_place: "Sorong",
        birth_date: "2001-07-22",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Mahasiswa",
        education: "SMA/SMK",
        phone: "084567890126",
        child_order: 2,
      },
    ],
  },
  {
    family_name: "Keluarga Kaliky",
    head_nik: "9201140802650020",
    head_name: "Abner Kaliky",
    head_birth_place: "Ambon",
    head_birth_date: "1965-08-04",
    head_gender: "Laki-laki",
    head_job: "Pensiunan PNS",
    head_education: "S1",
    head_phone: "085678901234",
    home_address: "Jl. Diponegoro No. 18, Sorong",
    wife_name: "Herlina Feto",
    members: [
      {
        nik: "9201140902680021",
        name: "Herlina Feto",
        birth_place: "Sorong",
        birth_date: "1968-09-16",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Ibu Rumah Tangga",
        education: "SMA/SMK",
        phone: "085678901235",
        child_order: null,
      },
      {
        nik: "9201141002900022",
        name: "Yosef Kaliky",
        birth_place: "Sorong",
        birth_date: "1990-10-12",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Dokter",
        education: "S2",
        phone: "085678901236",
        child_order: 1,
      },
      {
        nik: "9201141102920023",
        name: "Debora Kaliky",
        birth_place: "Sorong",
        birth_date: "1992-11-28",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Perawat",
        education: "D3",
        phone: "085678901237",
        child_order: 2,
      },
      {
        nik: "9201141202950024",
        name: "Joshua Kaliky",
        birth_place: "Sorong",
        birth_date: "1995-12-09",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Programmer",
        education: "S1",
        phone: "085678901238",
        child_order: 3,
      },
      {
        nik: "9201140103990025",
        name: "Grace Kaliky",
        birth_place: "Sorong",
        birth_date: "1999-01-17",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Mahasiswa",
        education: "SMA/SMK",
        phone: null,
        child_order: 4,
      },
    ],
  },
  {
    family_name: "Keluarga Wer",
    head_nik: "9201140203730026",
    head_name: "Marthen Wer",
    head_birth_place: "Sorong",
    head_birth_date: "1973-02-11",
    head_gender: "Laki-laki",
    head_job: "Sopir",
    head_education: "SMA/SMK",
    head_phone: "086789012345",
    home_address: "Jl. Kartini No. 56, Sorong",
    wife_name: "Ester Mone",
    members: [
      {
        nik: "9201140303760027",
        name: "Ester Mone",
        birth_place: "Sorong",
        birth_date: "1976-03-05",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Pedagang",
        education: "SMP",
        phone: "086789012346",
        child_order: null,
      },
      {
        nik: "9201140403000028",
        name: "Elisa Wer",
        birth_place: "Sorong",
        birth_date: "2000-04-20",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Karyawan Swasta",
        education: "D3",
        phone: "086789012347",
        child_order: 1,
      },
      {
        nik: "9201140503030029",
        name: "Tomas Wer",
        birth_place: "Sorong",
        birth_date: "2003-05-08",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMA/SMK",
        phone: null,
        child_order: 2,
      },
    ],
  },
  {
    family_name: "Keluarga Rumatora",
    head_nik: "9201140603690030",
    head_name: "Yusuf Rumatora",
    head_birth_place: "Fakfak",
    head_birth_date: "1969-06-14",
    head_gender: "Laki-laki",
    head_job: "Pedagang",
    head_education: "SMA/SMK",
    head_phone: "087890123456",
    home_address: "Jl. Pramuka No. 33, Sorong",
    wife_name: "Christina Sorong",
    members: [
      {
        nik: "9201140703720031",
        name: "Christina Sorong",
        birth_place: "Sorong",
        birth_date: "1972-07-21",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Pedagang",
        education: "SMP",
        phone: "087890123457",
        child_order: null,
      },
      {
        nik: "9201140803940032",
        name: "David Rumatora",
        birth_place: "Sorong",
        birth_date: "1994-08-09",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "TNI",
        education: "SMA/SMK",
        phone: "087890123458",
        child_order: 1,
      },
      {
        nik: "9201140903960033",
        name: "Hanna Rumatora",
        birth_place: "Sorong",
        birth_date: "1996-09-15",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Bidan",
        education: "D3",
        phone: "087890123459",
        child_order: 2,
      },
      {
        nik: "9201141003000034",
        name: "Isak Rumatora",
        birth_place: "Sorong",
        birth_date: "2000-10-01",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Mahasiswa",
        education: "SMA/SMK",
        phone: null,
        child_order: 3,
      },
    ],
  },
  {
    family_name: "Keluarga Krey",
    head_nik: "9201141103710035",
    head_name: "Hendrik Krey",
    head_birth_place: "Sorong",
    head_birth_date: "1971-11-30",
    head_gender: "Laki-laki",
    head_job: "Guru",
    head_education: "S1",
    head_phone: "088901234567",
    home_address: "Jl. Pendidikan No. 9, Sorong",
    wife_name: "Diana Bano",
    members: [
      {
        nik: "9201141203740036",
        name: "Diana Bano",
        birth_place: "Sorong",
        birth_date: "1974-12-10",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Guru",
        education: "S1",
        phone: "088901234568",
        child_order: null,
      },
      {
        nik: "9201140104970037",
        name: "Melky Krey",
        birth_place: "Sorong",
        birth_date: "1997-01-25",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Polisi",
        education: "SMA/SMK",
        phone: "088901234569",
        child_order: 1,
      },
      {
        nik: "9201140204990038",
        name: "Priska Krey",
        birth_place: "Sorong",
        birth_date: "1999-02-18",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Guru",
        education: "S1",
        phone: "088901234570",
        child_order: 2,
      },
      {
        nik: "9201140304020039",
        name: "Gideon Krey",
        birth_place: "Sorong",
        birth_date: "2002-03-06",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMA/SMK",
        phone: null,
        child_order: 3,
      },
      {
        nik: "9201140404060040",
        name: "Lidya Krey",
        birth_place: "Sorong",
        birth_date: "2006-04-12",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMP",
        phone: null,
        child_order: 4,
      },
      {
        nik: "9201140504100041",
        name: "Jonathan Krey",
        birth_place: "Sorong",
        birth_date: "2010-05-29",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Pelajar",
        education: "SD",
        phone: null,
        child_order: 5,
      },
    ],
  },
  {
    family_name: "Keluarga Mandowen",
    head_nik: "9201140604670042",
    head_name: "Simon Mandowen",
    head_birth_place: "Biak",
    head_birth_date: "1967-06-23",
    head_gender: "Laki-laki",
    head_job: "PNS",
    head_education: "S1",
    head_phone: "089012345678",
    home_address: "Jl. Kemiri No. 14, Sorong",
    wife_name: "Oktovina Feto",
    members: [
      {
        nik: "9201140704700043",
        name: "Oktovina Feto",
        birth_place: "Sorong",
        birth_date: "1970-07-18",
        gender: "Perempuan",
        family_status: "Istri",
        job: "PNS",
        education: "S1",
        phone: "089012345679",
        child_order: null,
      },
      {
        nik: "9201140804920044",
        name: "Imanuel Mandowen",
        birth_place: "Sorong",
        birth_date: "1992-08-04",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Insinyur",
        education: "S1",
        phone: "089012345680",
        child_order: 1,
      },
      {
        nik: "9201140904950045",
        name: "Feby Mandowen",
        birth_place: "Sorong",
        birth_date: "1995-09-11",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Apoteker",
        education: "S1",
        phone: "089012345681",
        child_order: 2,
      },
    ],
  },
  {
    family_name: "Keluarga Tabuni",
    head_nik: "9201141004760046",
    head_name: "Nehemia Tabuni",
    head_birth_place: "Wamena",
    head_birth_date: "1976-10-02",
    head_gender: "Laki-laki",
    head_job: "Wiraswasta",
    head_education: "SMA/SMK",
    head_phone: "081122334455",
    home_address: "Jl. Nusantara No. 67, Sorong",
    wife_name: "Rina Mone",
    members: [
      {
        nik: "9201141104790047",
        name: "Rina Mone",
        birth_place: "Sorong",
        birth_date: "1979-11-15",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Pedagang",
        education: "SMA/SMK",
        phone: "081122334456",
        child_order: null,
      },
      {
        nik: "9201141204020048",
        name: "Yehezkiel Tabuni",
        birth_place: "Sorong",
        birth_date: "2002-12-20",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Mahasiswa",
        education: "SMA/SMK",
        phone: "081122334457",
        child_order: 1,
      },
      {
        nik: "9201140105050049",
        name: "Nona Tabuni",
        birth_place: "Sorong",
        birth_date: "2005-01-08",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMA/SMK",
        phone: null,
        child_order: 2,
      },
      {
        nik: "9201140205080050",
        name: "Amos Tabuni",
        birth_place: "Sorong",
        birth_date: "2008-02-14",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMP",
        phone: null,
        child_order: 3,
      },
    ],
  },
  {
    family_name: "Keluarga Wambrauw",
    head_nik: "9201140305740051",
    head_name: "Alexander Wambrauw",
    head_birth_place: "Manokwari",
    head_birth_date: "1974-03-17",
    head_gender: "Laki-laki",
    head_job: "Tukang Bangunan",
    head_education: "SMP",
    head_phone: "082233445566",
    home_address: "Jl. Garuda No. 31, Sorong",
    wife_name: "Selvi Sorong",
    members: [
      {
        nik: "9201140405770052",
        name: "Selvi Sorong",
        birth_place: "Sorong",
        birth_date: "1977-04-09",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Ibu Rumah Tangga",
        education: "SD",
        phone: "082233445567",
        child_order: null,
      },
      {
        nik: "9201140505990053",
        name: "Alfredo Wambrauw",
        birth_place: "Sorong",
        birth_date: "1999-05-20",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Mekanik",
        education: "SMA/SMK",
        phone: "082233445568",
        child_order: 1,
      },
      {
        nik: "9201140605020054",
        name: "Yanti Wambrauw",
        birth_place: "Sorong",
        birth_date: "2002-06-15",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Mahasiswa",
        education: "SMA/SMK",
        phone: null,
        child_order: 2,
      },
    ],
  },
  {
    family_name: "Keluarga Ayomi",
    head_nik: "9201140705800055",
    head_name: "Benediktus Ayomi",
    head_birth_place: "Serui",
    head_birth_date: "1980-07-26",
    head_gender: "Laki-laki",
    head_job: "Karyawan Swasta",
    head_education: "D3",
    head_phone: "083344556677",
    home_address: "Jl. Merpati No. 5, Sorong",
    wife_name: "Verina Krey",
    members: [
      {
        nik: "9201140805830056",
        name: "Verina Krey",
        birth_place: "Sorong",
        birth_date: "1983-08-13",
        gender: "Perempuan",
        family_status: "Istri",
        job: "Ibu Rumah Tangga",
        education: "SMA/SMK",
        phone: "083344556678",
        child_order: null,
      },
      {
        nik: "9201140905060057",
        name: "Kevin Ayomi",
        birth_place: "Sorong",
        birth_date: "2006-09-01",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Pelajar",
        education: "SMP",
        phone: null,
        child_order: 1,
      },
      {
        nik: "9201141005090058",
        name: "Angel Ayomi",
        birth_place: "Sorong",
        birth_date: "2009-10-22",
        gender: "Perempuan",
        family_status: "Anak",
        job: "Pelajar",
        education: "SD",
        phone: null,
        child_order: 2,
      },
      {
        nik: "9201141105130059",
        name: "Rafael Ayomi",
        birth_place: "Sorong",
        birth_date: "2013-11-07",
        gender: "Laki-laki",
        family_status: "Anak",
        job: "Pelajar",
        education: "SD",
        phone: null,
        child_order: 3,
      },
    ],
  },
];

const seed = db.transaction(() => {
  for (const fam of families) {
    const { members, ...familyData } = fam;
    const result = insertFamily.run(familyData);
    const familyId = result.lastInsertRowid;

    for (const member of members) {
      insertMember.run({ ...member, family_id: familyId });
    }
  }
});

seed();

const famCount = db.prepare("SELECT COUNT(*) as c FROM families").get().c;
const memCount = db.prepare("SELECT COUNT(*) as c FROM members").get().c;
console.log(
  `Seed complete: ${famCount} families, ${memCount} members inserted.`,
);

db.close();
